# Generated by Django 2.1 on 2019-06-09 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage', models.FloatField()),
                ('reading_type', models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('GAS', 'Gas')], max_length=32)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('allowance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitComplex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govrent.UnitComplex'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='govrent.Unit'),
        ),
    ]
